version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: 
          name: build
          command: |
            $ProgressPreference = "SilentlyContinue"
            msbuild AMMEdit.csproj /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64|ARM" /p:BuildAppxUploadPackageForUap=true /p:AppxPackageSigningEnabled=false -restore
      - run:
          name: Compress AppPackages
          command: Compress-Archive -Path .\bin\Release\ -DestinationPath ./Release.zip
      - store_artifacts:
          path: ./Release.zip
workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build:
            context:
                - dotnet_build
